### ISSUE TITLE
ML Cookbook

### ISSUE THREAD

**Issue by jrtechs** [jrtechs/RandomScripts#17]
Create a collection of ML/AI algorithms in a sub directory called "ML Cookbook".

- [ ] Decision Trees
- [ ] Genetic Algorithms
- [ ] Perceptron
- [ ] Neural Network
- [ ] GAINS
- [ ] CCN
- [ ] Bayesian Optimization

**Comment by impratiksingh** [comment]
Hey jrtechs , I am happy to contribute on it. This is my first contribution so please forgive me if I ask too many questions.
1, What you actually want in this request , do you want .py files for each algorithms source code , of some working example.

**Comment by yoyogi009** [comment]
Hii jrtech , I am a student of ML engineering and I would love to contribute for this repo .I am working on perceptron network.

**Comment by jrtechs** [comment]
@yoyogi009 that is great!

**Comment by jrtechs** [comment]
@impratiksingh if you just include some documented python source files that would be amazing. You can include a test example in the main function.

**Comment by nancyanand2807** [comment]
I am including the python source file for perceptron network. Kindly review it.

**Comment by jrtechs** [comment]
@nancyanand2807 done :smile:
